last_change = 2026-01-02T18:02:37.352505Z
addr = 0x63d0
size = 0x108
name = "CClient::InitializeClientInfo"
type = "void"

[header]
name = "CClient::InitializeClientInfo"
addr = 0x63d0
type = "void"

[header.args]
