last_change = 2026-01-02T18:02:37.352505Z
addr = 0x3a000
size = 0x5c
name = "CommandLineMgr::sub_43B000"
type = "void"

[header]
name = "CommandLineMgr::sub_43B000"
addr = 0x3a000
type = "void"

[header.args]
