last_change = 2026-01-02T18:02:37.352505Z
addr = 0x1e59d0
size = 0x34
name = "GetFloatCommandLineAgr"
type = "float"

[header]
name = "GetFloatCommandLineAgr"
addr = 0x1e59d0
type = "float"

[header.args]
