last_change = 2026-01-02T18:02:37.352505Z
addr = 0x1e5ef0
size = 0x112
name = "CommandLineMgr::Init"
type = "void"

[header]
name = "CommandLineMgr::Init"
addr = 0x1e5ef0
type = "void"

[header.args]
