last_change = 2026-01-02T18:02:37.352505Z
addr = 0x281ea0
size = 0x7
name = "?WasExplicitlyAttached@ExternalContextBase@details@Concurrency@@QBE_NXZ"
type = "bool"

[header]
name = "?WasExplicitlyAttached@ExternalContextBase@details@Concurrency@@QBE_NXZ"
addr = 0x281ea0
type = "bool"

[header.args]
