last_change = 2026-01-09T19:50:22.843112Z
addr = 0x2db3b0
size = 0x14
name = "TryEnterCriticalSectionW"

[header]
last_change = 2026-01-09T19:50:22.843112Z
name = "TryEnterCriticalSectionW"
addr = 0x2db3b0

[header.args]
