last_change = 2026-01-02T18:02:37.353514Z
addr = 0x3389a0
size = 0x15
name = "Server::IsMyAndHomeWorld"
type = "BOOL"

[header]
name = "Server::IsMyAndHomeWorld"
addr = 0x3389a0
type = "BOOL"

[header.args]
