last_change = 2026-01-02T18:02:37.353514Z
addr = 0x338fb0
size = 0x5f
name = "Server::Handle_RPCEntityEvent"
type = "void"

[header]
name = "Server::Handle_RPCEntityEvent"
addr = 0x338fb0
type = "void"

[header.args]
