last_change = 2026-01-02T18:02:37.353514Z
addr = 0x331ec0
size = 0x7
name = "ModeGlobal::GetUsername"
type = "char *"

[header]
name = "ModeGlobal::GetUsername"
addr = 0x331ec0
type = "char *"

[header.args]
