last_change = 2026-01-02T18:02:37.353514Z
addr = 0x338a30
size = 0x13
name = "Server::Handle_RPCBeginSync"
type = "void"

[header]
name = "Server::Handle_RPCBeginSync"
addr = 0x338a30
type = "void"

[header.args]
