last_change = 2026-01-02T18:02:37.353514Z
addr = 0x3347b0
size = 0x12f
name = "FrontEndStateManager::Switch"
type = "char"

[header]
name = "FrontEndStateManager::Switch"
addr = 0x3347b0
type = "char"

[header.args]
