last_change = 2026-01-02T18:02:37.353514Z
addr = 0x338900
size = 0x19
name = "Server::Handle_RPCTimeSync"
type = "long long"

[header]
name = "Server::Handle_RPCTimeSync"
addr = 0x338900
type = "long long"

[header.args]
