last_change = 2026-01-02T18:02:37.353514Z
addr = 0x338f70
size = 0x33
name = "Server::Handle_RPCPartialChunkEditsSync"
type = "void"

[header]
name = "Server::Handle_RPCPartialChunkEditsSync"
addr = 0x338f70
type = "void"

[header.args]
