last_change = 2026-01-02T18:02:37.353514Z
addr = 0x338a10
size = 0x4
name = "Server::GetServerAdventureCRC"
type = "int *"

[header]
name = "Server::GetServerAdventureCRC"
addr = 0x338a10
type = "int *"

[header.args]
