last_change = 2026-01-02T18:02:37.353514Z
addr = 0x331e30
size = 0x7
name = "ModeGlobal::sub_732E30"
type = "int"

[header]
name = "ModeGlobal::sub_732E30"
addr = 0x331e30
type = "int"

[header.args]
