last_change = 2026-01-02T18:02:37.353514Z
addr = 0x34a770
size = 0x80
name = "PacketManager:Remove_RPCKillOccurred"
type = "void ***"

[header]
name = "PacketManager:Remove_RPCKillOccurred"
addr = 0x34a770
type = "void ***"

[header.args]
