last_change = 2026-01-02T18:02:37.353514Z
addr = 0x34afb0
size = 0x9a
name = "PacketManager::Add_RPCPlayerLeft"
type = "void"

[header]
name = "PacketManager::Add_RPCPlayerLeft"
addr = 0x34afb0
type = "void"

[header.args]
