last_change = 2026-01-02T18:02:37.353514Z
addr = 0x351e70
size = 0x69
name = "ClientHealthComponent::ParameterData::Read"
type = "char"

[header]
name = "ClientHealthComponent::ParameterData::Read"
addr = 0x351e70
type = "char"

[header.args]
