last_change = 2026-01-02T18:02:37.353514Z
addr = 0x358640
size = 0x27
name = "pv::world::client::ClientWorldService::sub_759640"
type = "unsigned int *"

[header]
name = "pv::world::client::ClientWorldService::sub_759640"
addr = 0x358640
type = "unsigned int *"

[header.args]
