last_change = 2026-01-02T18:02:37.353514Z
addr = 0x3662e0
size = 0x61
name = "pv::entity_manager::List::sub_7672E0"
type = "void"

[header]
name = "pv::entity_manager::List::sub_7672E0"
addr = 0x3662e0
type = "void"

[header.args]
