last_change = 2026-01-02T18:02:37.353514Z
addr = 0x36abc0
size = 0xcb
name = "UserInterface2D::sub_76BBC0"
type = "char"

[header]
name = "UserInterface2D::sub_76BBC0"
addr = 0x36abc0
type = "char"

[header.args]
