last_change = 2026-01-02T18:02:37.353514Z
addr = 0x36e800
size = 0x76
name = "EntityInstance::GetInventoryComponent"
type = "InventoryComponent *"

[header]
name = "EntityInstance::GetInventoryComponent"
addr = 0x36e800
type = "InventoryComponent *"

[header.args]
