last_change = 2026-01-02T18:02:37.353514Z
addr = 0x37b080
size = 0xa
name = "CharacterList::sub_77C080"
type = "BOOL"

[header]
name = "CharacterList::sub_77C080"
addr = 0x37b080
type = "BOOL"

[header.args]
