last_change = 2026-01-02T18:02:37.353514Z
addr = 0x3717c0
size = 0x6c
name = "ModeHomeWorld::UpdateEntities"
type = "int"

[header]
name = "ModeHomeWorld::UpdateEntities"
addr = 0x3717c0
type = "int"

[header.args]
