last_change = 2026-01-02T18:02:37.353514Z
addr = 0x37b1d0
size = 0x17
name = "??0CharacterList@@QAE@XZ"
type = "CharacterList *"

[header]
name = "??0CharacterList@@QAE@XZ"
addr = 0x37b1d0
type = "CharacterList *"

[header.args]
