last_change = 2026-01-02T18:02:37.353514Z
addr = 0x388470
size = 0x48f
name = "FrontEndState::DownloadCharacter::sub_789470"
type = "void"

[header]
name = "FrontEndState::DownloadCharacter::sub_789470"
addr = 0x388470
type = "void"

[header.args]
