last_change = 2026-01-02T18:02:37.353514Z
addr = 0x38f240
size = 0x7
name = "RakNetServer::GetConnectionState"
type = "char"

[header]
name = "RakNetServer::GetConnectionState"
addr = 0x38f240
type = "char"

[header.args]
