last_change = 2026-01-02T18:02:37.353514Z
addr = 0x385770
size = 0x130
name = "FrontEndState::CharacterCreation::sub_786770"
type = "void"

[header]
name = "FrontEndState::CharacterCreation::sub_786770"
addr = 0x385770
type = "void"

[header.args]
