last_change = 2026-01-02T18:02:37.353514Z
addr = 0x387420
size = 0x12
name = "??0SGLogin@FrontEndState@@QAE@XZ"
type = "FrontEndState *"

[header]
name = "??0SGLogin@FrontEndState@@QAE@XZ"
addr = 0x387420
type = "FrontEndState *"

[header.args]
