last_change = 2026-01-02T18:02:37.353514Z
addr = 0x382c30
size = 0x12
name = "??0InitialSync@GameState@@QAE@XZ"
type = "GameState::InitialSync *"

[header]
name = "??0InitialSync@GameState@@QAE@XZ"
addr = 0x382c30
type = "GameState::InitialSync *"

[header.args]
