last_change = 2026-01-02T18:02:37.353514Z
addr = 0x392160
size = 0x7f
name = "RakNet::BitStream::sub_793160"
type = "char"

[header]
name = "RakNet::BitStream::sub_793160"
addr = 0x392160
type = "char"

[header.args]
