last_change = 2026-01-02T18:02:37.353514Z
addr = 0x391e00
size = 0x54
name = "ClientEquippedItemComponent::sub_792E00"
type = "unsigned int *"

[header]
name = "ClientEquippedItemComponent::sub_792E00"
addr = 0x391e00
type = "unsigned int *"

[header.args]
