last_change = 2026-01-02T18:02:37.353514Z
addr = 0x3ada40
size = 0x69
name = "VoxelDamageComponent::sub_7AEA40"
type = "bool"

[header]
name = "VoxelDamageComponent::sub_7AEA40"
addr = 0x3ada40
type = "bool"

[header.args]
