last_change = 2026-01-02T18:02:37.353514Z
addr = 0x3ad270
size = 0x143
name = "ClientVoxelDamageComponent::sub_7AE270"
type = "BOOL"

[header]
name = "ClientVoxelDamageComponent::sub_7AE270"
addr = 0x3ad270
type = "BOOL"

[header.args]
