last_change = 2026-01-02T18:02:37.353514Z
addr = 0x3b5ef0
size = 0x4
name = "pv::world::GetUnknown"
type = "pv::world::unknown *"

[header]
name = "pv::world::GetUnknown"
addr = 0x3b5ef0
type = "pv::world::unknown *"

[header.args]
