last_change = 2026-01-02T18:02:37.353514Z
addr = 0x3e8320
size = 0x3c1
name = "BaseRakNetServer::Session::Send_RPCPerformVoxelActions"
type = "int"

[header]
name = "BaseRakNetServer::Session::Send_RPCPerformVoxelActions"
addr = 0x3e8320
type = "int"

[header.args]
