last_change = 2026-01-02T18:02:37.353514Z
addr = 0x3e78e0
size = 0x17
name = "??0FrontEndState@@QAE@XZ"
type = "FrontEndState *"

[header]
name = "??0FrontEndState@@QAE@XZ"
addr = 0x3e78e0
type = "FrontEndState *"

[header.args]
