last_change = 2026-01-02T18:02:37.353514Z
addr = 0x3f3ba0
size = 0x10
name = "??0DNameNode@@IAE@XZ_2"
type = "DNameNode *"

[header]
name = "??0DNameNode@@IAE@XZ_2"
addr = 0x3f3ba0
type = "DNameNode *"

[header.args]
