last_change = 2026-01-02T18:02:37.353514Z
addr = 0x3fe010
size = 0x76
name = "EntityInstance::GetClientInteractionComponent"
type = "ClientInteractionComponent *"

[header]
name = "EntityInstance::GetClientInteractionComponent"
addr = 0x3fe010
type = "ClientInteractionComponent *"

[header.args]
