last_change = 2026-01-02T18:02:37.353514Z
addr = 0x40e4c0
size = 0xb3
name = "pv::component_list::Insert"
type = "pv::component_list::node *"

[header]
name = "pv::component_list::Insert"
addr = 0x40e4c0
type = "pv::component_list::node *"

[header.args]
