last_change = 2026-01-02T18:02:37.353514Z
addr = 0x402a60
size = 0x12
name = "??0ClientPlaceVoxelAction@@QAE@XZ"
type = "ClientPlaceVoxelAction *"

[header]
name = "??0ClientPlaceVoxelAction@@QAE@XZ"
addr = 0x402a60
type = "ClientPlaceVoxelAction *"

[header.args]
