last_change = 2026-01-02T18:02:37.353514Z
addr = 0x4084b0
size = 0x99
name = "ClientUISettingsComponent_sub_8094B0"
type = "char"

[header]
name = "ClientUISettingsComponent_sub_8094B0"
addr = 0x4084b0
type = "char"

[header.args]
