last_change = 2026-01-02T18:02:37.353514Z
addr = 0x4061b0
size = 0x174
name = "CharacterStateComponent::GetParameterIndexFromName"
type = "char"

[header]
name = "CharacterStateComponent::GetParameterIndexFromName"
addr = 0x4061b0
type = "char"

[header.args]
