last_change = 2026-01-02T18:02:37.354510Z
addr = 0x44d740
size = 0x1c
name = "??0ClientTimeOfDayComponent@@QAE@XZ"
type = "unsigned int *"

[header]
name = "??0ClientTimeOfDayComponent@@QAE@XZ"
addr = 0x44d740
type = "unsigned int *"

[header.args]
