last_change = 2026-01-03T15:37:49.127130Z
addr = 0x446cc0
size = 0x54
name = "TreeComponent::sub_847CC0"

[header]
last_change = 2026-01-03T15:37:49.127130Z
name = "TreeComponent::sub_847CC0"
addr = 0x446cc0

[header.args.0x0]
offset = 0x0
name = "this"
type = "TreeComponent *"
size = 0x4
