last_change = 2026-01-02T18:02:37.353514Z
addr = 0x443d10
size = 0x4a
name = "ClientCharacterPhysicsComponent::OnEvent"
type = "void"

[header]
name = "ClientCharacterPhysicsComponent::OnEvent"
addr = 0x443d10
type = "void"

[header.args]
