last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4557a0
size = 0xc
name = "pv::world::WorldService::sub_8567A0"
type = "Chunk *"

[header]
name = "pv::world::WorldService::sub_8567A0"
addr = 0x4557a0
type = "Chunk *"

[header.args]
