last_change = 2026-01-02T18:02:37.354510Z
addr = 0x454a40
size = 0x5a
name = "TopLevelExceptionFilter"
type = "LONG"

[header]
name = "TopLevelExceptionFilter"
addr = 0x454a40
type = "LONG"

[header.args]
