last_change = 2026-01-02T18:02:37.354510Z
addr = 0x468b70
size = 0xce
name = "Chunk::Unknown::sub_869B70"
type = "void"

[header]
name = "Chunk::Unknown::sub_869B70"
addr = 0x468b70
type = "void"

[header.args]
