last_change = 2026-01-02T18:02:37.354510Z
addr = 0x468970
size = 0x1f1
name = "Chunk::Unknown::sub_869970"
type = "void"

[header]
name = "Chunk::Unknown::sub_869970"
addr = 0x468970
type = "void"

[header.args]
