last_change = 2026-01-02T18:02:37.354510Z
addr = 0x464720
size = 0x16b
name = "GeoData::ParseBiomes"
type = "char"

[header]
name = "GeoData::ParseBiomes"
addr = 0x464720
type = "char"

[header.args]
