last_change = 2026-01-02T18:02:37.354510Z
addr = 0x468790
size = 0x1ca
name = "Chunk::Unknown::sub_869790"
type = "void"

[header]
name = "Chunk::Unknown::sub_869790"
addr = 0x468790
type = "void"

[header.args]
