last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4782f0
size = 0x7f
name = "pv::entity_manager::sub_8792F0"
type = "void"

[header]
name = "pv::entity_manager::sub_8792F0"
addr = 0x4782f0
type = "void"

[header.args]
