last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4751f0
size = 0x6f
name = "EntityInstance::OnEvent"
type = "void"

[header]
name = "EntityInstance::OnEvent"
addr = 0x4751f0
type = "void"

[header.args]
