last_change = 2026-01-02T18:02:37.354510Z
addr = 0x47fd30
size = 0x58
name = "??0BaseResourceItem@@QAE@XZ"
type = "BaseResourceInstance *"

[header]
name = "??0BaseResourceItem@@QAE@XZ"
addr = 0x47fd30
type = "BaseResourceInstance *"

[header.args]
