last_change = 2026-01-02T18:02:37.354510Z
addr = 0x47caa0
size = 0x20
name = "InventoryItemComponent::sub_87DAA0"
type = "BaseResourceInstance *"

[header]
name = "InventoryItemComponent::sub_87DAA0"
addr = 0x47caa0
type = "BaseResourceInstance *"

[header.args]
