last_change = 2026-01-02T18:02:37.354510Z
addr = 0x478eb0
size = 0xbc
name = "pv::entity_manager::List::sub_879EB0"
type = "void"

[header]
name = "pv::entity_manager::List::sub_879EB0"
addr = 0x478eb0
type = "void"

[header.args]
