last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4754f0
size = 0x51
name = "EntityInstance::AddComponent"
type = "void"

[header]
name = "EntityInstance::AddComponent"
addr = 0x4754f0
type = "void"

[header.args]
