last_change = 2026-01-02T18:02:37.354510Z
addr = 0x488cd0
size = 0x228
name = "HealthComponent::ParameterData::sub_889CD0"
type = "char"

[header]
name = "HealthComponent::ParameterData::sub_889CD0"
addr = 0x488cd0
type = "char"

[header.args]
