last_change = 2026-01-02T18:02:37.354510Z
addr = 0x488270
size = 0x38c
name = "HealthComponent::sub_889270"
type = "int"

[header]
name = "HealthComponent::sub_889270"
addr = 0x488270
type = "int"

[header.args]
