last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4874c0
size = 0x98
name = "EquippedItemComponent::ParameterData::Print"
type = "char"

[header]
name = "EquippedItemComponent::ParameterData::Print"
addr = 0x4874c0
type = "char"

[header.args]
