last_change = 2026-01-02T18:02:37.354510Z
addr = 0x489850
size = 0x130
name = "InventoryComponent::sub_88A850"
type = "char"

[header]
name = "InventoryComponent::sub_88A850"
addr = 0x489850
type = "char"

[header.args]
