last_change = 2026-01-02T18:02:37.354510Z
addr = 0x48bec0
size = 0xd
name = "?set_bound@?$source_link_manager@V?$multi_link_registry@V?$ISource@W4agent_status@Concurrency@@@Concurrency@@@Concurrency@@@Concurrency@@QAEXI@Z_0"

[header]
name = "?set_bound@?$source_link_manager@V?$multi_link_registry@V?$ISource@W4agent_status@Concurrency@@@Concurrency@@@Concurrency@@@Concurrency@@QAEXI@Z_0"
addr = 0x48bec0

[header.args]
