last_change = 2026-01-02T18:02:37.354510Z
addr = 0x499770
size = 0xdd
name = "BaseRakNetServer::Send"
type = "int"

[header]
name = "BaseRakNetServer::Send"
addr = 0x499770
type = "int"

[header.args]
