last_change = 2026-01-02T18:02:37.354510Z
addr = 0x491dd0
size = 0x4e
name = "Component::sub_892DD0"
type = "unsigned int *"

[header]
name = "Component::sub_892DD0"
addr = 0x491dd0
type = "unsigned int *"

[header.args]
