last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4a15d0
size = 0x22
name = "Entity::Parameter::SetFlag"
type = "void"

[header]
name = "Entity::Parameter::SetFlag"
addr = 0x4a15d0
type = "void"

[header.args]
