last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4b80e0
size = 0x73
name = "FeatureUnlockComponent::ParameterData::Read"
type = "char"

[header]
name = "FeatureUnlockComponent::ParameterData::Read"
addr = 0x4b80e0
type = "char"

[header.args]
