last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4cfc20
size = 0x55
name = "??0PlayerAspectsComponent@@QAE@XZ"
type = "PlayerAspectsComponent *"

[header]
name = "??0PlayerAspectsComponent@@QAE@XZ"
addr = 0x4cfc20
type = "PlayerAspectsComponent *"

[header.args]
