last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4d2fc0
size = 0x87
name = "UISettingsComponent::ParameterData::Write"
type = "char"

[header]
name = "UISettingsComponent::ParameterData::Write"
addr = 0x4d2fc0
type = "char"

[header.args]
