last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4d46d0
size = 0x110
name = "VoxelDamageComponent::GetNextDamagedVoxelIndex"
type = "unsigned int"

[header]
name = "VoxelDamageComponent::GetNextDamagedVoxelIndex"
addr = 0x4d46d0
type = "unsigned int"

[header.args]
