last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4d0f90
size = 0x9
name = "??0action@pv@@QAE@XZ"
type = "pv::action *"

[header]
name = "??0action@pv@@QAE@XZ"
addr = 0x4d0f90
type = "pv::action *"

[header.args]
