last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4d6d40
size = 0x6
name = "BreatheComponent::sub_8D7D40"
type = "char"

[header]
name = "BreatheComponent::sub_8D7D40"
addr = 0x4d6d40
type = "char"

[header.args]
