last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4df260
size = 0x12b
name = "PlaceVoxelAction::sub_8E0260"
type = "bool"

[header]
name = "PlaceVoxelAction::sub_8E0260"
addr = 0x4df260
type = "bool"

[header.args]
