last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4d5a20
size = 0x42
name = "VoxelDamageComponent::ParameterData::Write"
type = "char"

[header]
name = "VoxelDamageComponent::ParameterData::Write"
addr = 0x4d5a20
type = "char"

[header.args]
