last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4ee7c0
size = 0xd0
name = "ClientTreeComponent::ApplyDescriptionOffsetChain"
type = "Vector3 *"

[header]
name = "ClientTreeComponent::ApplyDescriptionOffsetChain"
addr = 0x4ee7c0
type = "Vector3 *"

[header.args]
