last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4ed1a0
size = 0x10
name = "InventoryEntity::sub_8EE1A0"
type = "void"

[header]
name = "InventoryEntity::sub_8EE1A0"
addr = 0x4ed1a0
type = "void"

[header.args]
