last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4eb8c0
size = 0x116
name = "pv::component_manager::sub_8EC8C0"
type = "void"

[header]
name = "pv::component_manager::sub_8EC8C0"
addr = 0x4eb8c0
type = "void"

[header.args]
