last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4f7680
size = 0x75
name = "NodeComponent::ParameterData::Print"
type = "char"

[header]
name = "NodeComponent::ParameterData::Print"
addr = 0x4f7680
type = "char"

[header.args]
