last_change = 2026-01-02T18:02:37.354510Z
addr = 0x4f73b0
size = 0x263
name = "TimeOfDayComponent::ParameterData::sub_8F83B0"
type = "char"

[header]
name = "TimeOfDayComponent::ParameterData::sub_8F83B0"
addr = 0x4f73b0
type = "char"

[header.args]
