last_change = 2026-01-02T18:02:37.354510Z
addr = 0x511490
size = 0x7
name = "?_Release@_NonReentrantLock@details@Concurrency@@QAEXXZ"
type = "void"

[header]
name = "?_Release@_NonReentrantLock@details@Concurrency@@QAEXXZ"
addr = 0x511490
type = "void"

[header.args]
