last_change = 2026-01-02T18:02:37.354510Z
addr = 0x5116c0
size = 0x10
name = "EquippedItemComponent::EquippedAction::sub_9126C0"
type = "void"

[header]
name = "EquippedItemComponent::EquippedAction::sub_9126C0"
addr = 0x5116c0
type = "void"

[header.args]
