last_change = 2026-01-02T18:02:37.357515Z
addr = 0x60e4f0
size = 0xd
name = "?MarkAsVirtualProcessorRoot@ExecutionResource@details@Concurrency@@QAEXPAVVirtualProcessorRoot@23@@Z_1"
type = "void"

[header]
name = "?MarkAsVirtualProcessorRoot@ExecutionResource@details@Concurrency@@QAEXPAVVirtualProcessorRoot@23@@Z_1"
addr = 0x60e4f0
type = "void"

[header.args]
