last_change = 2026-01-02T18:02:37.357515Z
addr = 0x6424f0
size = 0x7
name = "?GetCompletionListEvent@UMSSchedulerProxy@details@Concurrency@@QBEPAXXZ_0"
type = "void *"

[header]
name = "?GetCompletionListEvent@UMSSchedulerProxy@details@Concurrency@@QBEPAXXZ_0"
addr = 0x6424f0
type = "void *"

[header.args]
