last_change = 2026-01-02T18:02:37.357515Z
addr = 0x672260
size = 0x5
name = "j_??1RakString@RakNet@@QAE@XZ_0"
type = "void"

[header]
name = "j_??1RakString@RakNet@@QAE@XZ_0"
addr = 0x672260
type = "void"

[header.args]
