last_change = 2026-01-02T18:02:37.357515Z
addr = 0x673720
size = 0x2d
name = "?ReverseBytesInPlace@BitStream@RakNet@@SAXPAEI@Z"
type = "void"

[header]
name = "?ReverseBytesInPlace@BitStream@RakNet@@SAXPAEI@Z"
addr = 0x673720
type = "void"

[header.args]
