last_change = 2026-01-02T18:02:37.357515Z
addr = 0x673a50
size = 0xc4
name = "?WriteBits@BitStream@RakNet@@QAEXPBEI_N@Z"
type = "char"

[header]
name = "?WriteBits@BitStream@RakNet@@QAEXPBEI_N@Z"
addr = 0x673a50
type = "char"

[header.args]
