last_change = 2026-01-02T18:02:37.358524Z
addr = 0x6c7ee0
size = 0x6
name = "SSL_get_current_cipher"
type = "int"

[header]
name = "SSL_get_current_cipher"
addr = 0x6c7ee0
type = "int"

[header.args]
