last_change = 2026-01-02T18:02:37.358524Z
addr = 0x6c7c7c
size = 0x6
name = "X509_NAME_get_index_by_NID"
type = "int"

[header]
name = "X509_NAME_get_index_by_NID"
addr = 0x6c7c7c
type = "int"

[header.args]
