last_change = 2026-01-02T18:02:37.358524Z
addr = 0x6c7bb0
size = 0x6
name = "SSL_CTX_use_certificate_chain_file"
type = "int"

[header]
name = "SSL_CTX_use_certificate_chain_file"
addr = 0x6c7bb0
type = "int"

[header.args]
