last_change = 2026-01-02T18:02:37.358524Z
addr = 0x6c7ea4
size = 0x6
name = "SSL_CTX_load_verify_locations"
type = "int"

[header]
name = "SSL_CTX_load_verify_locations"
addr = 0x6c7ea4
type = "int"

[header.args]
