last_change = 2026-01-02T18:02:37.358524Z
addr = 0x6c7c10
size = 0x6
name = "CRYPTO_cleanup_all_ex_data"
type = "int"

[header]
name = "CRYPTO_cleanup_all_ex_data"
addr = 0x6c7c10
type = "int"

[header.args]
