last_change = 2026-01-02T18:02:37.358524Z
addr = 0x6d7290
size = 0xd
name = "?SetOwningContext@WorkQueue@details@Concurrency@@QAEXPAVContextBase@23@@Z_2"
type = "void"

[header]
name = "?SetOwningContext@WorkQueue@details@Concurrency@@QAEXPAVContextBase@23@@Z_2"
addr = 0x6d7290
type = "void"

[header.args]
