last_change = 2026-01-02T18:02:37.358524Z
addr = 0x6db300
size = 0xd
name = "?SetOwningContext@WorkQueue@details@Concurrency@@QAEXPAVContextBase@23@@Z_3"
type = "void"

[header]
name = "?SetOwningContext@WorkQueue@details@Concurrency@@QAEXPAVContextBase@23@@Z_3"
addr = 0x6db300
type = "void"

[header.args]
