last_change = 2026-01-02T18:02:37.358524Z
addr = 0x6e3aa0
size = 0x10
name = "??0DNameNode@@IAE@XZ_3"
type = "DNameNode *"

[header]
name = "??0DNameNode@@IAE@XZ_3"
addr = 0x6e3aa0
type = "DNameNode *"

[header.args]
