last_change = 2026-01-02T18:02:37.358524Z
addr = 0x6e45a0
size = 0xd
name = "?_SetRuntimeOwnsLifetime@_UnrealizedChore@details@Concurrency@@QAEX_N@Z_0"
type = "void"

[header]
name = "?_SetRuntimeOwnsLifetime@_UnrealizedChore@details@Concurrency@@QAEX_N@Z_0"
addr = 0x6e45a0
type = "void"

[header.args]
