last_change = 2026-01-02T18:02:37.358524Z
addr = 0x6f8e95
size = 0x9b
name = "___security_init_cookie"
type = "void"

[header]
name = "___security_init_cookie"
addr = 0x6f8e95
type = "void"

[header.args]
