last_change = 2026-01-02T18:02:37.359505Z
addr = 0x6fc4b9
size = 0x23
name = "__abnormal_termination"
type = "int"

[header]
name = "__abnormal_termination"
addr = 0x6fc4b9
type = "int"

[header.args]
