last_change = 2026-01-02T18:02:37.358524Z
addr = 0x6f3163
size = 0x45a
name = "?_store_winword@@YAHPAUlocaleinfo_struct@@HPBUtm@@PAPADPAIPAU__lc_time_data@@@Z"
type = "int"

[header]
name = "?_store_winword@@YAHPAUlocaleinfo_struct@@HPBUtm@@PAPADPAIPAU__lc_time_data@@@Z"
addr = 0x6f3163
type = "int"

[header.args]
