last_change = 2026-01-02T18:02:37.359505Z
addr = 0x6fc8e0
size = 0xd6
name = "__local_unwind4"
type = "unsigned int"

[header]
name = "__local_unwind4"
addr = 0x6fc8e0
type = "unsigned int"

[header.args]
