last_change = 2026-01-02T18:02:37.358524Z
addr = 0x6f50ff
size = 0x60
name = "?_CallCatchBlock2@@YAPAXPAUEHRegistrationNode@@PBU_s_FuncInfo@@PAXHK@Z"
type = "void *"

[header]
name = "?_CallCatchBlock2@@YAPAXPAUEHRegistrationNode@@PBU_s_FuncInfo@@PAXHK@Z"
addr = 0x6f50ff
type = "void *"

[header.args]
