last_change = 2026-01-02T18:02:37.358524Z
addr = 0x6f2dab
size = 0x3b8
name = "?_expandtime@@YAHPAUlocaleinfo_struct@@DPBUtm@@PAPADPAIPAU__lc_time_data@@I@Z"
type = "int"

[header]
name = "?_expandtime@@YAHPAUlocaleinfo_struct@@DPBUtm@@PAPADPAIPAU__lc_time_data@@I@Z"
addr = 0x6f2dab
type = "int"

[header.args]
