last_change = 2026-01-02T18:02:37.358524Z
addr = 0x6f4db4
size = 0x54
name = "?_UnwindNestedFrames@@YGXPAUEHRegistrationNode@@PAUEHExceptionRecord@@@Z"
type = "void"

[header]
name = "?_UnwindNestedFrames@@YGXPAUEHRegistrationNode@@PAUEHExceptionRecord@@@Z"
addr = 0x6f4db4
type = "void"

[header.args]
