last_change = 2026-01-02T18:02:37.359505Z
addr = 0x707351
size = 0xc
name = "?getLastChar@DNameStatusNode@@UBEDXZ"
type = "char"

[header]
name = "?getLastChar@DNameStatusNode@@UBEDXZ"
addr = 0x707351
type = "char"

[header.args]
