last_change = 2026-01-02T18:02:37.359505Z
addr = 0x705851
size = 0x375
name = "?FindHandler@@YAXPAUEHExceptionRecord@@PAUEHRegistrationNode@@PAU_CONTEXT@@PAXPBU_s_FuncInfo@@EH1@Z"
type = "void"

[header]
name = "?FindHandler@@YAXPAUEHExceptionRecord@@PAUEHRegistrationNode@@PAU_CONTEXT@@PAXPBU_s_FuncInfo@@EH1@Z"
addr = 0x705851
type = "void"

[header.args]
