last_change = 2026-01-02T18:02:37.359505Z
addr = 0x707a8d
size = 0x9b
name = "??0DName@@QAE@_J@Z"
type = "DName *"

[header]
name = "??0DName@@QAE@_J@Z"
addr = 0x707a8d
type = "DName *"

[header.args]
