last_change = 2026-01-02T18:02:37.359505Z
addr = 0x701d6b
size = 0x57
name = "___check_float_string_0"
type = "int"

[header]
name = "___check_float_string_0"
addr = 0x701d6b
type = "int"

[header.args]
