last_change = 2026-01-02T18:02:37.359505Z
addr = 0x7071f0
size = 0x1f
name = "?UScore@UnDecorator@@SAPBDW4Tokens@@@Z"

[header]
name = "?UScore@UnDecorator@@SAPBDW4Tokens@@@Z"
addr = 0x7071f0

[header.args]
