last_change = 2026-01-02T18:02:37.359505Z
addr = 0x709910
size = 0xe1
name = "?getScopedName@UnDecorator@@CA?AVDName@@XZ"

[header]
name = "?getScopedName@UnDecorator@@CA?AVDName@@XZ"
addr = 0x709910

[header.args]
