last_change = 2026-01-02T18:02:37.359505Z
addr = 0x70bdd9
size = 0x1b1
name = "?getPrimaryDataType@UnDecorator@@CA?AVDName@@ABV2@@Z"

[header]
name = "?getPrimaryDataType@UnDecorator@@CA?AVDName@@ABV2@@Z"
addr = 0x70bdd9

[header.args]
