last_change = 2026-01-02T18:02:37.359505Z
addr = 0x707ee4
size = 0x54
name = "?getVdispMapType@UnDecorator@@CA?AVDName@@ABV2@@Z"

[header]
name = "?getVdispMapType@UnDecorator@@CA?AVDName@@ABV2@@Z"
addr = 0x707ee4

[header.args]
