last_change = 2026-01-02T18:02:37.359505Z
addr = 0x7072be
size = 0x17
name = "?getString@charNode@@UBEPADPAD0@Z"
type = "char *"

[header]
name = "?getString@charNode@@UBEPADPAD0@Z"
addr = 0x7072be
type = "char *"

[header.args]
