last_change = 2026-01-02T18:02:37.359505Z
addr = 0x70e089
size = 0xe7
name = "?__crtGetStringTypeA_stat@@YAHPAUlocaleinfo_struct@@KPBDHPAGHHH@Z"
type = "int"

[header]
name = "?__crtGetStringTypeA_stat@@YAHPAUlocaleinfo_struct@@KPBDHPAGHHH@Z"
addr = 0x70e089
type = "int"

[header.args]
