last_change = 2026-01-02T18:02:37.359505Z
addr = 0x70b1a5
size = 0x59f
name = "?getDataIndirectType@UnDecorator@@CA?AVDName@@ABV2@PBD0H@Z"

[header]
name = "?getDataIndirectType@UnDecorator@@CA?AVDName@@ABV2@PBD0H@Z"
addr = 0x70b1a5

[header.args]
