last_change = 2026-01-02T18:02:37.359505Z
addr = 0x707d04
size = 0x24
name = "??HDName@@QBE?AV0@ABV0@@Z"
type = "int"

[header]
name = "??HDName@@QBE?AV0@ABV0@@Z"
addr = 0x707d04
type = "int"

[header.args]
