last_change = 2026-01-02T18:02:37.359505Z
addr = 0x707a1f
size = 0x6e
name = "??0DName@@QAE@_K@Z"
type = "DName *"

[header]
name = "??0DName@@QAE@_K@Z"
addr = 0x707a1f
type = "DName *"

[header.args]
