last_change = 2026-01-02T18:02:37.359505Z
addr = 0x70574a
size = 0x107
name = "?FindHandlerForForeignException@@YAXPAUEHExceptionRecord@@PAUEHRegistrationNode@@PAU_CONTEXT@@PAXPBU_s_FuncInfo@@HH1@Z"
type = "void"

[header]
name = "?FindHandlerForForeignException@@YAXPAUEHExceptionRecord@@PAUEHRegistrationNode@@PAU_CONTEXT@@PAXPBU_s_FuncInfo@@HH1@Z"
addr = 0x70574a
type = "void"

[header.args]
