last_change = 2026-01-02T18:02:37.359505Z
addr = 0x7072d5
size = 0x2a
name = "??0pDNameNode@@QAE@PAVDName@@@Z"
type = "pDNameNode *"

[header]
name = "??0pDNameNode@@QAE@PAVDName@@@Z"
addr = 0x7072d5
type = "pDNameNode *"

[header.args]
