last_change = 2026-01-02T18:02:37.359505Z
addr = 0x707cb9
size = 0x4b
name = "?getVCallThunkType@UnDecorator@@CA?AVDName@@XZ"

[header]
name = "?getVCallThunkType@UnDecorator@@CA?AVDName@@XZ"
addr = 0x707cb9

[header.args]
