last_change = 2026-01-02T18:02:37.359505Z
addr = 0x705270
size = 0x76
name = "?IsInExceptionSpec@@YAEPAUEHExceptionRecord@@PBU_s_ESTypeList@@@Z"
type = "unsigned char"

[header]
name = "?IsInExceptionSpec@@YAEPAUEHExceptionRecord@@PBU_s_ESTypeList@@@Z"
addr = 0x705270
type = "unsigned char"

[header.args]
