last_change = 2026-01-02T18:02:37.359505Z
addr = 0x723b08
size = 0x6
name = "DirectInput8Create"
type = "HRESULT"

[header]
name = "DirectInput8Create"
addr = 0x723b08
type = "HRESULT"

[header.args]
