last_change = 2026-01-02T18:02:37.359505Z
addr = 0x723b32
size = 0x6
name = "GetFileVersionInfoSizeA"
type = "DWORD"

[header]
name = "GetFileVersionInfoSizeA"
addr = 0x723b32
type = "DWORD"

[header.args]
