last_change = 2026-01-02T18:02:37.359505Z
addr = 0x823e54
size = 0x6
name = "SHGetKnownFolderPath"
type = "HRESULT"

[header]
name = "SHGetKnownFolderPath"
addr = 0x823e54
type = "HRESULT"

[header.args]
