last_change = 2026-01-09T20:02:38.552713Z
name = "TempByteAllocatorGlobals"
size = 0xfc8

[members.0x0]
name = "init_flags"
offset = 0x0
type = "int32_t"
size = 0x4

[members.0x4]
name = "spin_proxy"
offset = 0x4
type = "int32_t"
size = 0x4

[members.0x8]
name = "CriticalSection"
offset = 0x8
type = "_RTL_CRITICAL_SECTION"
size = 0x18

[members.0x20]
name = "alloc_count"
offset = 0x20
type = "int32_t"
size = 0x4

[members.0x24]
name = "pool_padding"
offset = 0x24
type = "char[4]"
size = 0x4

[members.0x28]
name = "byte_pool"
offset = 0x28
type = "char[4000]"
size = 0xfa0
